### ISSUE TITLE
bdr_init_copy doesn't notice if postmaster fails to start

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#100]
bdr_init_copy will hang indefinitely at what looks like it's 2nd or 3rd server startup if the datadir permissions are not 0700. The postmaster complains and exits:

```
[2-1] FATAL:  55000: data directory "/data/pgdata" has group or world access
[3-1] DETAIL:  Permissions should be u=rwx (0700).
 [4-1] LOCATION:  checkDataDir, postmaster.c:1388
```

but `bdr_init_copy` doesn't notice and waits indefinitely in:

```
#0  0x00007f0cc1b33433 in __select_nocancel () from /lib64/libc.so.6
#1  0x0000000000405b9a in pg_usleep (microsec=<value optimized out>) at pgsleep.c:53
#2  0x00000000004030fa in wait_postmaster_connection (connstr=0x10983d0 "user=postgres dbname=xx host='xxxx' port=5432") at bdr_init_copy.c:1362
#3  0x0000000000403fd8 in main (argc=<value optimized out>, argv=<value optimized out>) at bdr_init_copy.c:419
```

**Comment by PJMODOS** [comment]
That's probably because the return value of the command is never checked ;)
